services:
  frontend:
    build:
      context: ./public  # Контекст сборки для фронтенда
      dockerfile: Dockerfile  # Имя Dockerfile для фронтенда
    ports:
      - "5000:5000"

  server:
    build:
      context: .  # Контекст сборки для сервера
      dockerfile: Dockerfile  # Имя Dockerfile для сервера
    ports:
      - "3000:3000"
    volumes:
      - ./database.sqlite:/app/database.sqlite
      - ./db.js:/app/db.js
    environment:
      - DATABASE_PATH=/app/database.sqlite

  database:
    image: nouchka/sqlite3:latest 
    volumes:
      - db_data:/data/db
    environment:
      - SQLITE_DATABASE=/data/db/database.sqlite

volumes:
  db_data: